# Generated by Django 2.2.4 on 2020-11-14 19:33

from django.db import migrations, models
import django.db.models.deletion
import openrepairplatform.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0031_auto_20201114_2033'),
        ('inventory', '0006_auto_20201114_1856'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiagnosisOrRepair',
        ),
        migrations.RemoveField(
            model_name='repair',
            name='actions',
        ),
        migrations.RemoveField(
            model_name='repair',
            name='event',
        ),
        migrations.RemoveField(
            model_name='repair',
            name='fixer',
        ),
        migrations.RemoveField(
            model_name='repair',
            name='repair_folder',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='stuff_ptr',
        ),
        migrations.RemoveField(
            model_name='repairfolder',
            name='Stuff',
        ),
        migrations.AddField(
            model_name='action',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='diagnosisorrepairstep',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Action'),
        ),
        migrations.AddField(
            model_name='diagnosisorrepairstep',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.Event'),
        ),
        migrations.AddField(
            model_name='diagnosisorrepairstep',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.RepairFolder'),
        ),
        migrations.AddField(
            model_name='diagnosisorrepairstep',
            name='observation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Observation'),
        ),
        migrations.AddField(
            model_name='diagnosisorrepairstep',
            name='reasoning',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Reasoning'),
        ),
        migrations.AddField(
            model_name='diagnosisorrepairstep',
            name='repair_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisorrepairstep',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Status'),
        ),
        migrations.AddField(
            model_name='historicalstuff',
            name='information',
            field=openrepairplatform.fields.CleanHTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='reasoning',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='repairfolder',
            name='open_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repairfolder',
            name='steps',
            field=models.ManyToManyField(to='inventory.DiagnosisOrRepairStep'),
        ),
        migrations.AddField(
            model_name='repairfolder',
            name='stuff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Stuff'),
        ),
        migrations.AddField(
            model_name='status',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='stuff',
            name='information',
            field=openrepairplatform.fields.CleanHTMLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Part',
        ),
        migrations.DeleteModel(
            name='Repair',
        ),
        migrations.DeleteModel(
            name='Tool',
        ),
    ]
