# Generated by Django 2.2.4 on 2020-11-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20201114_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repairfolder',
            name='steps',
            field=models.ManyToManyField(blank=True, null=True, to='inventory.DiagnosisOrRepairStep'),
        ),
    ]
