# Generated by Django 2.2.4 on 2020-11-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20201114_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff',
            name='folders',
            field=models.ManyToManyField(blank=True, related_name='repair_folders', to='inventory.RepairFolder'),
        ),
        migrations.AlterField(
            model_name='repairfolder',
            name='steps',
            field=models.ManyToManyField(blank=True, to='inventory.DiagnosisOrRepairStep'),
        ),
    ]
