# Generated by Django 2.2.4 on 2020-11-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20201114_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosisorrepairstep',
            name='folder',
        ),
        migrations.RemoveField(
            model_name='repairfolder',
            name='stuff',
        ),
        migrations.RemoveField(
            model_name='stuff',
            name='folders',
        ),
        migrations.AddField(
            model_name='stuff',
            name='folder',
            field=models.ManyToManyField(blank=True, to='inventory.RepairFolder'),
        ),
    ]
