# Generated by Django 2.2.4 on 2020-11-14 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20201114_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stuff',
            name='folder',
        ),
        migrations.AddField(
            model_name='repairfolder',
            name='stuff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Stuff'),
        ),
    ]
