# Generated by Django 2.2.4 on 2020-11-14 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20201114_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosisorrepairstep',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.RepairFolder'),
        ),
    ]
