# Generated by Django 2.2.4 on 2020-11-14 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_diagnosisorrepairstep_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repairfolder',
            name='steps',
        ),
        migrations.AlterField(
            model_name='diagnosisorrepairstep',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steps', to='inventory.RepairFolder'),
        ),
        migrations.AlterField(
            model_name='repairfolder',
            name='stuff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folders', to='inventory.Stuff'),
        ),
    ]
