# Generated by Django 2.2.4 on 2020-11-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20201114_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='defect',
        ),
        migrations.AddField(
            model_name='device',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.DeleteModel(
            name='Defect',
        ),
    ]
