# Generated by Django 2.2.4 on 2020-11-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20201115_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='slug',
            field=models.SlugField(blank=True, default='', unique=True),
        ),
    ]
