# Generated by Django 2.2.4 on 2020-11-15 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import openrepairplatform.fields
import openrepairplatform.utils
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0015_auto_20201115_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='devices/', validators=[openrepairplatform.utils.validate_image], verbose_name='Image'),
        ),
        migrations.CreateModel(
            name='HistoricalDevice',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('description', openrepairplatform.fields.CleanHTMLField(blank=True, null=True)),
                ('picture', models.TextField(blank=True, max_length=100, null=True, validators=[openrepairplatform.utils.validate_image], verbose_name='Image')),
                ('slug', models.SlugField(blank=True, default='')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('brand', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.Brand')),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.Category')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical device',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
