# Generated by Django 2.2.4 on 2020-11-21 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0031_auto_20201114_2033'),
        ('inventory', '0016_auto_20201115_1457'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DiagnosisOrRepairStep',
            new_name='Intervention',
        ),
        migrations.AlterField(
            model_name='stuff',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stuffs', to='inventory.Device'),
        ),
    ]
