# Generated by Django 2.2.4 on 2020-11-21 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_auto_20201121_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to='inventory.RepairFolder'),
        ),
    ]
