# Generated by Django 2.2.4 on 2020-11-27 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_auto_20201121_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='action',
            field=models.ForeignKey(blank=True, help_text="Qu'avez-vous fait ?", null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Action'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='observation',
            field=models.ForeignKey(blank=True, help_text='Quel est (ou était) le problème ?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Observation'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='reasoning',
            field=models.ForeignKey(blank=True, help_text='Quel en est ou serait la cause ?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Reasoning'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='status',
            field=models.ForeignKey(blank=True, help_text="Quel est le résultat de l'action ?", null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Status'),
        ),
    ]
