# Generated by Django 2.2.4 on 2020-12-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_auto_20201204_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstuff',
            name='is_visible',
            field=models.BooleanField(default=False, help_text="Cet appareil est-il visible du public ? (par exemple, s'il est mis en vente)", verbose_name='Appareil visible'),
        ),
        migrations.AddField(
            model_name='stuff',
            name='is_visible',
            field=models.BooleanField(default=False, help_text="Cet appareil est-il visible du public ? (par exemple, s'il est mis en vente)", verbose_name='Appareil visible'),
        ),
    ]
