# Generated by Django 2.2.4 on 2020-12-06 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_auto_20201204_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='member_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_stuffs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='organization_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_stuffs', to='user.Organization'),
        ),
    ]
