# Generated by Django 2.2.4 on 2020-12-08 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_auto_20201206_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstuff',
            name='state',
            field=models.CharField(choices=[('B', 'En panne'), ('W', 'Fonctionnel'), ('D', 'Désassemblé'), ('F', 'En réparation'), ('O', 'Réparé'), ('T', 'Evaporé'), ('P', 'Partiel')], default='B', max_length=1, verbose_name='Etat'),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='place',
            field=models.ForeignKey(blank=True, help_text="Où se trouve l'appareil ?", null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.Place', verbose_name='Localisation'),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='state',
            field=models.CharField(choices=[('B', 'En panne'), ('W', 'Fonctionnel'), ('D', 'Désassemblé'), ('F', 'En réparation'), ('O', 'Réparé'), ('T', 'Evaporé'), ('P', 'Partiel')], default='B', max_length=1, verbose_name='Etat'),
        ),
    ]
