# Generated by Django 2.2.4 on 2020-12-20 16:13

from django.db import migrations, models
import django.db.models.deletion
import openrepairplatform.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_auto_20201213_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstuff',
            name='information',
            field=openrepairplatform.fields.CleanHTMLField(blank=True, help_text="D'où vient-il, a t'il des caractéristiques spéciales... bref, tout ce qui peut le décrire", null=True, verbose_name='Information optionnelles sur cet objet'),
        ),
        migrations.AlterField(
            model_name='historicalstuff',
            name='is_visible',
            field=models.BooleanField(default=False, help_text="Cet objet est-il visible du public ? (par exemple, s'il est mis en vente)", verbose_name='Objet visible'),
        ),
        migrations.AlterField(
            model_name='historicalstuff',
            name='place',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="Où se trouve l'objet ?", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='location.Place', verbose_name='Localisation'),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='information',
            field=openrepairplatform.fields.CleanHTMLField(blank=True, help_text="D'où vient-il, a t'il des caractéristiques spéciales... bref, tout ce qui peut le décrire", null=True, verbose_name='Information optionnelles sur cet objet'),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='is_visible',
            field=models.BooleanField(default=False, help_text="Cet objet est-il visible du public ? (par exemple, s'il est mis en vente)", verbose_name='Objet visible'),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='place',
            field=models.ForeignKey(blank=True, help_text="Où se trouve l'objet ?", null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.Place', verbose_name='Localisation'),
        ),
    ]
