# Generated by Django 2.2.4 on 2020-12-21 10:04

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_auto_20201221_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='links',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='historicaldevice',
            name='links',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None),
        ),
    ]
