# Generated by Django 2.2.20 on 2021-05-11 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_auto_20201221_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='repair_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='repairfolder',
            name='open_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
