# Generated by Django 3.2.2 on 2021-05-28 11:47

from django.db import migrations
import openrepairplatform.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_auto_20210511_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstuff',
            name='information',
            field=openrepairplatform.fields.CleanHTMLField(blank=True, help_text=("D'où vient-il, a t'il des caractéristiques spéciales... bref, tout ce qui peut le décrire",), null=True, verbose_name='Information optionnelles sur cet objet'),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='information',
            field=openrepairplatform.fields.CleanHTMLField(blank=True, help_text=("D'où vient-il, a t'il des caractéristiques spéciales... bref, tout ce qui peut le décrire",), null=True, verbose_name='Information optionnelles sur cet objet'),
        ),
    ]
