# Generated by Django 4.2.17 on 2025-11-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_auto_20210528_1347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaldevice',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical device', 'verbose_name_plural': 'historical devices'},
        ),
        migrations.AlterModelOptions(
            name='historicalstuff',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical stuff', 'verbose_name_plural': 'historical stuffs'},
        ),
        migrations.AlterField(
            model_name='historicaldevice',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalstuff',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
