# Generated by Django 4.2.17 on 2025-11-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_alter_historicaldevice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='model',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldevice',
            name='model',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
