# Generated by Django 4.2.17 on 2026-01-14 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_alter_historicalcustomuser_options_and_more'),
        ('inventory', '0031_alter_device_model_alter_historicaldevice_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThermalPrinter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('profile', models.CharField(blank=True, help_text="Optionnel. Profil de l'imprimante thermique. Liste ici : liste dispo ici : https://python-escpos.readthedocs.io/en/latest/printer_profiles/available-profiles.html", max_length=250, null=True)),
                ('ip', models.GenericIPAddressField()),
                ('port', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.organization')),
            ],
        ),
    ]
