# Generated by Django 4.2.17 on 2025-12-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_alter_device_model_alter_historicaldevice_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThermalPrinter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('profile', models.CharField(blank=True, help_text="Profil de l'imprimante thermique. Liste ici : liste dispo ici : https://python-escpos.readthedocs.io/en/latest/printer_profiles/available-profiles.html", max_length=250, null=True)),
                ('ip', models.GenericIPAddressField()),
                ('port', models.IntegerField(blank=True, null=True)),
                ('api_key', models.CharField(default='c12da4942ff4406fb1d708a2a79498be', max_length=250)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
