# Generated by Django 2.2.4 on 2020-08-29 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20200829_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstuff',
            name='device',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.Device'),
        ),
        migrations.AddField(
            model_name='stuff',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device', to='inventory.Device'),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='member_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='organization_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_owner', to='user.Organization'),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='place', to='location.Place'),
        ),
    ]
