# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-08 12:00
from __future__ import unicode_literals

import address.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('address', '0002_auto_20160213_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Abilities')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=150, verbose_name='Title')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start date and time')),
                ('ends_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='End date and time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendees', models.ManyToManyField(related_name='attendee_user', to=settings.AUTH_USER_MODEL, verbose_name='Attendees')),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Event type')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Organization name')),
                ('active', models.BooleanField(verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.SmallIntegerField(choices=[(0, 'Visitor'), (10, 'Member'), (20, 'Volunteer'), (30, 'Admin')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(default='', verbose_name='Description')),
                ('type', models.CharField(choices=[('rc', 'Repair café'), ('sc', 'School')], default='ot', max_length=2, verbose_name='Type')),
                ('picture', models.ImageField(upload_to='', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', address.models.AddressField(default='', on_delete=django.db.models.deletion.CASCADE, to='address.Address', verbose_name='Postal address')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationVolunteer',
            fields=[
                ('organizationperson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='plateformeweb.OrganizationPerson')),
                ('tagline', models.TextField(verbose_name='Tagline')),
                ('abilities', models.ManyToManyField(to='plateformeweb.Abilities')),
            ],
            bases=('plateformeweb.organizationperson',),
        ),
        migrations.AddField(
            model_name='organizationperson',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationperson',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plateformeweb.Organization'),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ManyToManyField(to='plateformeweb.Place'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizers',
            field=models.ManyToManyField(related_name='organizer_user', to=settings.AUTH_USER_MODEL, verbose_name='Organizers'),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='plateformeweb.EventType'),
        ),
        migrations.CreateModel(
            name='OrganizationAdministrator',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('plateformeweb.organizationperson',),
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('plateformeweb.organizationperson',),
        ),
        migrations.CreateModel(
            name='OrganizationVisitor',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('plateformeweb.organizationperson',),
        ),
        migrations.AlterUniqueTogether(
            name='organizationperson',
            unique_together=set([('organization', 'member', 'role')]),
        ),
    ]
