# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-11 10:42
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plateformeweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedEvent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('plateformeweb.event',),
        ),
        migrations.AddField(
            model_name='event',
            name='available_seats',
            field=models.IntegerField(blank=True, default=0, verbose_name='Available seats'),
        ),
        migrations.AddField(
            model_name='event',
            name='publish_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publication date and time'),
        ),
        migrations.AddField(
            model_name='event',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='title', unique=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='name', unique=True),
        ),
        migrations.AddField(
            model_name='place',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='attendee_user', to=settings.AUTH_USER_MODEL, verbose_name='Attendees'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='plateformeweb.Place'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizers',
            field=models.ManyToManyField(blank=True, related_name='organizer_user', to=settings.AUTH_USER_MODEL, verbose_name='Organizers'),
        ),
        migrations.AlterField(
            model_name='place',
            name='picture',
            field=models.ImageField(upload_to='places/', verbose_name='Image'),
        ),
    ]
