# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-03 08:59
from __future__ import unicode_literals

from django.db import migrations
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('plateformeweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description',
            field=django_markdown.models.MarkdownField(default='', verbose_name='Place description'),
        ),
    ]
