# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-14 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plateformeweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plateformeweb.Organization'),
        ),
    ]
