# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-16 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateformeweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='price',
            field=models.IntegerField(blank=True, default=5, verbose_name='Price'),
        ),
    ]
