# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plateformeweb', '0002_auto_20171117_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='registration_date',
        ),
    ]
