# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-14 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plateformeweb', '0002_auto_20181214_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='owner',
        ),
        migrations.AddField(
            model_name='activity',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plateformeweb.Organization'),
        ),
    ]
