# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-11 13:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plateformeweb', '0002_auto_20180503_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField()),
                ('is_organizer', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
        migrations.RemoveField(
            model_name='event',
            name='organizers',
        ),
        migrations.RemoveField(
            model_name='event',
            name='presents',
        ),
        migrations.AddField(
            model_name='eventparticipation',
            name='Event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='plateformeweb.Event', verbose_name='Event'),
        ),
        migrations.AddField(
            model_name='eventparticipation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
