# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-11 15:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plateformeweb', '0003_auto_20180511_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventparticipation',
            name='Event',
        ),
        migrations.RemoveField(
            model_name='eventparticipation',
            name='user',
        ),
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='attendee_user', to=settings.AUTH_USER_MODEL, verbose_name='Attendees'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizers',
            field=models.ManyToManyField(blank=True, related_name='organizer_user', to=settings.AUTH_USER_MODEL, verbose_name='Organizers'),
        ),
        migrations.AddField(
            model_name='event',
            name='presents',
            field=models.ManyToManyField(blank=True, related_name='present_user', to=settings.AUTH_USER_MODEL, verbose_name='Presents'),
        ),
        migrations.DeleteModel(
            name='EventParticipation',
        ),
    ]
