# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-19 15:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plateformeweb', '0003_auto_20171219_0813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationperson',
            old_name='member',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='organizationperson',
            unique_together=set([('organization', 'user', 'role')]),
        ),
    ]
