# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-23 13:34
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import plateformeweb.models


class Migration(migrations.Migration):

    dependencies = [
        ('plateformeweb', '0004_auto_20180511_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Type')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='place',
            name='type',
            field=models.ForeignKey(on_delete=models.SET(plateformeweb.models.PlaceType.get_other_place), to='plateformeweb.PlaceType', verbose_name='Type'),
        ),
    ]
