# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-28 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plateformeweb', '0005_auto_20180523_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.SmallIntegerField(choices=[(0, 'Visitor'), (10, 'Member'), (20, 'Volunteer'), (30, 'Admin')], default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='organizationperson',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plateformeweb.Role'),
        ),
    ]
