# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-28 10:49
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('plateformeweb', '0006_auto_20180528_0921'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='organization',
            managers=[
                ('visitors', django.db.models.manager.Manager()),
            ],
        ),
    ]
