# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-28 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plateformeweb', '0007_auto_20180528_1049'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='organization',
            managers=[
            ],
        ),
    ]
