# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-28 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateformeweb', '0008_auto_20180528_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationperson',
            name='role',
            field=models.SmallIntegerField(choices=[(0, 'Visitor'), (10, 'Member'), (20, 'Volunteer'), (30, 'Admin')], default=0),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
