# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-28 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plateformeweb', '0009_auto_20180528_1118'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganizationAdministrator',
        ),
        migrations.CreateModel(
            name='OrganizationAdministrator',
            fields=[
                ('organizationperson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='plateformeweb.OrganizationPerson')),
            ],
            bases=('plateformeweb.organizationperson',),
        ),
    ]
