# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-28 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plateformeweb', '0010_auto_20180528_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationadministrator',
            name='organizationperson_ptr',
        ),
        migrations.DeleteModel(
            name='OrganizationAdministrator',
        ),
        migrations.CreateModel(
            name='OrganizationAdministrator',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('plateformeweb.organizationperson',),
        ),
    ]
