# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-27 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plateformeweb', '0011_auto_20180528_1147'),
        ('plateformeweb', '0002_auto_20180711_0848'),
    ]

    operations = [
    ]
