version: '3'

services:
  db:
    image: postgis/postgis
    container_name: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - openrepairplatform-db:/var/lib/postgresql/data
      - ./deployment/saves-bdd:/saves-bdd
    networks:
      - openrepairplatform-db
  openrepairplatform:
    build:
      dockerfile: ./deployment/django/Dockerfile
      target: production
      args:
        - DOMAINDNS=preprod.reparons.org
        - DOMAINS=localhost 127.0.0.1 [::1]
    container_name: openrepairplatform
    env_file:
      - .env
    volumes:
      - openrepairplatform_static:/srv/static
      - openrepairplatform_media:/srv/media
    depends_on:
      - db
    networks:
      - openrepairplatform
      - openrepairplatform-db
    restart: unless-stopped
  nginx:
    image: nginx:latest
    container_name: openrepairplatform_nginx
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
    depends_on:
      - openrepairplatform
      - certbot
    volumes:
      - ./deployment/nginx/templates/openrepairplatform.conf:/etc/nginx/templates/default.conf.template:ro
      - ./deployment/certbot/data/:/var/www/certbot/ 
      - ./deployment/certbot/letsencrypt/:/etc/nginx/ssl/
      - ./deployment/nginx/uwsgi_params:/srv/uwsgi_params:ro
      - ./deployment/nginx/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf:ro
      - openrepairplatform_static:/srv/static:ro
      - openrepairplatform_media:/srv/media:ro
    networks:
      - openrepairplatform
    restart: unless-stopped
  certbot:
    image: certbot/certbot:latest
    container_name: openrepairplatform_certbot
    volumes: 
      - ./deployment/certbot/data/:/var/www/certbot/ 
      - ./deployment/certbot/letsencrypt/:/etc/letsencrypt/
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    env_file:
      - .env
    networks:
      - openrepairplatform
networks:
  openrepairplatform:
  openrepairplatform-db:
volumes:
  openrepairplatform-db:
  openrepairplatform_media:
  openrepairplatform_static:
