version: '3'

services:
  db:
    image: postgis/postgis
    container_name: postgres
    env_file:
      - .env.prod
    ports:
      - 5432:5432
    volumes:
      - openrepairplatform-db:/var/lib/postgresql/data
      - ./deployment/saves-bdd:/saves-bdd
    networks:
      - openrepairplatform
  openrepairplatform:
    build:
      dockerfile: ./deployment/django/Dockerfile
      target: production
      args:
        - DOMAINDNS=reparons.soude
        - DOMAINS=localhost 127.0.0.1 [::1]
    ############# From docker hub image 
    #image: openrepairplatform-openrepairplatform:latest
    container_name: openrepairplatform
    env_file:
      - .env.prod
    volumes:
      - ./deployment/openrepairplatform_data/openrepairplatform_static:/srv/static
      - ./deployment/openrepairplatform_data/openrepairplatform_media:/srv/media
    depends_on:
      - db
    networks:
      - openrepairplatform
    restart: unless-stopped
  nginx:
    image: nginx:latest
    container_name: openrepairplatform_nginx
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env.prod
    volumes:
      - ./deployment/nginx/templates/openrepairplatform.conf:/etc/nginx/templates/default.conf.template
      #- ./deployment/nginx/templates/openrepairplatform.conf:/etc/nginx/templates/default.conf.template
      #- ./deployment/nginx/nginx-snippet.conf:/etc/nginx/snippets/ssl-params.conf
      #- ./deployment/nginx/uwsgi_params:/srv/uwsgi_params
      - ./deployment/certbot/www:/var/www/certbot/:ro
      - ./deployment/openrepairplatform_data/openrepairplatform_static:/srv/static:ro
      - ./deployment/openrepairplatform_data/openrepairplatform_media:/srv/media:ro
    #command: openssl dhparam -out /etc/ssl/certsdhparam.pem 4096
    networks:
      - openrepairplatform
    depends_on:
      - openrepairplatform 
    restart: unless-stopped
  certbot:
    image: certbot/certbot:latest
    links:
      - nginx
    depends_on:
      - nginx
    volumes: 
      - ./deployment/certbot/www/:/var/www/certbot/:rw 
      - ./deployment/certbot/conf/:/etc/lestencrypt/:rw 
      - ./deployment/certbot/lib/letsencrypt:/var/lib/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env.prod
    restart: unless-stopped
    networks:
      - openrepairplatform
networks:
  openrepairplatform:
volumes:
  certs:
  openrepairplatform-db: 
