version: '3'

services:
  db:
    image: postgres:11
    volumes:
      - $PWD/postgres_data:/var/lib/postgresql/data
    env_file:
      - deployment/postgres/postgres.env
    ports:
      - 5433:5432
  django:
    # container that will use the deployment image: useful for developping in a production-ready environment
    build:
      context: .
      dockerfile: ./deployment/django/Dockerfile
    image: ateliersoude_python
    volumes:
      - $PWD/ateliersoude:/srv/app/ateliersoude
      - $PWD/ateliersoude_media:/srv/app/media
      - $PWD/ateliersoude_static:/srv/app/static
      - $PWD/deployment/django:/srv/deployment
    ports:
      - 8000:8000
      - 5678:5678
    depends_on:
      - db
    working_dir: /srv/app
    environment:
      - DJANGO_SETTINGS_MODULE=ateliersoude.settings.dev_docker
      - EMAIL_PASSWORD=iop@iop.com
      - SECRET_KEY=iop
    command:
      - /bin/bash
      - -c
      - |
        sed -i "s/{{SECRET_KEY}}/${SECRET_KEY}/" /etc/cron.d/ateliersoude
        sed -i "s/{{EMAIL_PASSWORD}}/${EMAIL_PASSWORD}/" /etc/cron.d/ateliersoude
        service cron start
        chown -R ateliersoude:ateliersoude /srv/*
        python3 -m pip install ptvsd django-debug-toolbar
        python3 manage.py migrate
        python3 manage.py shell -c "from ateliersoude.user.models import CustomUser; CustomUser.objects.create_superuser('admin@example.com', 'adminpass')" || true
        python3 manage.py collectstatic --noinput
        python3 -m ptvsd --host 0.0.0.0 --port 5678 manage.py runserver --noreload 0.0.0.0:8000
  djangotests:
    # container that will be used to run the tests. it uses sqlite
    build:
      context: .
      dockerfile: ./deployment/django/Dockerfile
    image: ateliersoude_testspython
    volumes:
      - $PWD/ateliersoude:/srv/app/ateliersoude
      - $PWD/ateliersoude_media:/srv/media
      - $PWD/ateliersoude_static:/srv/static
      - $PWD/deployment/django:/srv/deployment
    ports:
      - 8001:8000
    working_dir: /srv/app
    environment:
      - DJANGO_SETTINGS_MODULE=ateliersoude.settings.tests_docker
    command:
      - /bin/bash
      - -c
      - |
        sed -i "s/{{SECRET_KEY}}/${SECRET_KEY}/" /etc/cron.d/ateliersoude
        sed -i "s/{{EMAIL_PASSWORD}}/${EMAIL_PASSWORD}/" /etc/cron.d/ateliersoude
        service cron start
        chown -R ateliersoude:ateliersoude /srv/*
        python3 -m pip install ptvsd django-debug-toolbar
        python3 manage.py migrate
        python3 manage.py shell -c "from ateliersoude.user.models import CustomUser; CustomUser.objects.create_superuser('admin@example.com', 'adminpass')" || true
        python3 manage.py collectstatic --noinput
        python3 -m ptvsd --host 0.0.0.0 --port 5678 manage.py runserver --noreload 0.0.0.0:8000
  selenium:
    build:
      context: .
      dockerfile: ./ateliersoude/integration_tests/selenium/Dockerfile
    image: selenium_image
    volumes:
      - /dev/shm:/dev/shm
      - ./ateliersoude/integration_tests:/tests
    ports:
      - 4444:4444
      - 5900:5900
      - 5679:5678
    depends_on:
      - django
    environment:
      - VNC_NO_PASSWORD=1
