version: '3'

services:
  db:
    image: postgis/postgis
    container_name: postgres
    env_file:
      - .env
    volumes:
      - openrepairplatform-db:/var/lib/postgresql/data
      - ./deployment/saves-bdd:/saves-bdd
      - ./deployment/saves-bdd:/srv/saves-bdd 
    ports: # uncomment for dev env
      - 5432:5432 # uncomment for dev env
    networks:
      - openrepairplatform
  openrepairplatform: 
    build:
      dockerfile: ./deployment/django/Dockerfile
      target: developpement 
    container_name: openrepairplatform
    env_file:
      - .env
    volumes:
      - ./openrepairplatform/static/:/srv/static
      - ./deployment/openrepairplatform_data/openrepairplatform_media/:/srv/media
      - ../OpenRepairPlatform:/srv/app
      - ./deployment/saves-bdd:/srv/saves-bdd 
    command: bash -c "cd /srv/app/openrepairplatform/static/ && npm i && cd /srv/app/deployment/django && ./start-dev.sh" # uncomment for dev env
    ports: 
      - 80:80 
      - 5678:5678 
      - 5679:5679 
      - 35729:35729 
    depends_on:
      - db
    networks:
      - openrepairplatform
    restart: unless-stopped
networks:
  openrepairplatform:
volumes:
  certs:
  openrepairplatform-db: 
