version: '3'

services:
  db:
    image: postgis/postgis
    container_name: postgres
    env_file:
      - .env.prod
    ports:
      - 5432:5432
    volumes:
      - openrepairplatform-db:/var/lib/postgresql/data
      - ./deployment/saves-bdd:/saves-bdd
    networks:
      - openrepairplatform
  openrepairplatform:
    build:
      dockerfile: ./deployment/django/Dockerfile
      target: production
      args:
        - DOMAINDNS=preprod.reparons.org
        - DOMAINS=localhost 127.0.0.1 [::1]
    container_name: openrepairplatform
    env_file:
      - .env.prod
    volumes:
      - ./deployment/openrepairplatform_data/openrepairplatform_static:/srv/static
      - ./deployment/openrepairplatform_data/openrepairplatform_media:/srv/media
    depends_on:
      - db
    networks:
      - openrepairplatform
    restart: unless-stopped
  nginx:
    image: nginx:latest
    container_name: openrepairplatform_nginx
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env.prod
    volumes:
      - ./deployment/nginx/templates/openrepairplatform.conf:/etc/nginx/templates/default.conf.template:ro
      - ./deployment/certbot/data/:/var/www/certbot/ 
      - ./deployment/certbot/letsencrypt/:/etc/letsencrypt/
      - ./deployment/openrepairplatform_data/openrepairplatform_static:/srv/static:ro
      - ./deployment/openrepairplatform_data/openrepairplatform_media:/srv/media:ro
    networks:
      - openrepairplatform
    depends_on:
      - openrepairplatform
      - certbot
    restart: unless-stopped
  certbot:
    image: certbot/certbot:latest
    depends_on:
      - nginx
    volumes: 
      - ./deployment/certbot/data/:/var/www/certbot/ 
      - ./deployment/certbot/letsencrypt/:/etc/letsencrypt/
    command: >-
             certonly --reinstall --webroot --webroot-path=/var/www/certbot
             --email ${EMAIL} --agree-tos --no-eff-email
             -d ${DOMAIN}
    env_file:
      - .env.prod
    networks:
      - openrepairplatform
networks:
  openrepairplatform:
volumes:
  openrepairplatform-db: 
