# Generated by Django 2.2 on 2019-05-21 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20190520_1648'),
        ('event', '0007_historicalactivity_historicalcondition_historicalevent'),
    ]

    operations = [
    ]
