# Generated by Django 2.2 on 2019-05-21 15:14

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_merge_20190521_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalactivity',
            name='description',
            field=tinymce.models.HTMLField(default='', verbose_name='Activity description'),
        ),
        migrations.AlterField(
            model_name='historicalcondition',
            name='description',
            field=tinymce.models.HTMLField(default='', verbose_name='Condition description'),
        ),
    ]
