# Generated by Django 2.2 on 2019-05-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_auto_20190521_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='available_seats',
            field=models.PositiveIntegerField(default=0, verbose_name='Available seats'),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='available_seats',
            field=models.PositiveIntegerField(default=0, verbose_name='Available seats'),
        ),
    ]
