# Generated by Django 2.2 on 2019-05-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_auto_20190527_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalparticipation',
            name='saved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participation',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
