# Generated by Django 2.2 on 2019-06-04 10:54

import ateliersoude.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_auto_20190527_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=ateliersoude.fields.CleanHTMLField(default='', verbose_name='Activity description'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='description',
            field=ateliersoude.fields.CleanHTMLField(default='', verbose_name='Condition description'),
        ),
        migrations.AlterField(
            model_name='historicalactivity',
            name='description',
            field=ateliersoude.fields.CleanHTMLField(default='', verbose_name='Activity description'),
        ),
        migrations.AlterField(
            model_name='historicalcondition',
            name='description',
            field=ateliersoude.fields.CleanHTMLField(default='', verbose_name='Condition description'),
        ),
    ]
