# Generated by Django 2.2.3 on 2019-09-18 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_auto_20190918_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='nedded_organizers',
            new_name='needed_organizers',
        ),
        migrations.RenameField(
            model_name='historicalevent',
            old_name='nedded_organizers',
            new_name='needed_organizers',
        ),
    ]
