# Generated by Django 2.2.3 on 2019-08-22 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_merge_20190715_1033'),
        ('event', '0019_merge_20190708_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalparticipation',
            name='fee',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.Fee'),
        ),
        migrations.AddField(
            model_name='participation',
            name='fee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.Fee'),
            preserve_default=False,
        ),
    ]
