# Generated by Django 2.2.3 on 2019-08-22 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0021_auto_20190822_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='fee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Fee'),
        ),
    ]
