# Generated by Django 2.2.3 on 2020-02-08 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0026_auto_20200125_2050'),
        ('event', '0025_merge_20200129_1738'),
    ]

    operations = [
    ]
