# Generated by Django 2.2 on 2019-05-20 14:48

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customuser_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=tinymce.models.HTMLField(blank=True, default='', verbose_name='bio'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=tinymce.models.HTMLField(default='', verbose_name='Activity description'),
        ),
    ]
