# Generated by Django 2.2 on 2019-05-21 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190520_1648'),
        ('user', '0004_historicalcustomuser_historicalorganization'),
    ]

    operations = [
    ]
