# Generated by Django 2.2 on 2019-05-28 14:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190521_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='actives',
            field=models.ManyToManyField(blank=True, related_name='active_organizations', to=settings.AUTH_USER_MODEL),
        ),
    ]
