# Generated by Django 2.2 on 2019-05-27 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190521_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorganization',
            name='advised_fee',
            field=models.PositiveIntegerField(default=0, verbose_name='Advised contribution'),
        ),
        migrations.AddField(
            model_name='historicalorganization',
            name='min_fee',
            field=models.PositiveIntegerField(default=0, verbose_name='Minimum contribution'),
        ),
        migrations.AddField(
            model_name='organization',
            name='advised_fee',
            field=models.PositiveIntegerField(default=0, verbose_name='Advised contribution'),
        ),
        migrations.AddField(
            model_name='organization',
            name='min_fee',
            field=models.PositiveIntegerField(default=0, verbose_name='Minimum contribution'),
        ),
        migrations.CreateModel(
            name='MembershipFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_payment', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='Amount paid')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='fees_paid', through='user.MembershipFee', to=settings.AUTH_USER_MODEL),
        ),
    ]
