# Generated by Django 2.2 on 2019-06-04 10:54

import ateliersoude.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20190531_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=ateliersoude.fields.CleanHTMLField(blank=True, default='', verbose_name='bio'),
        ),
        migrations.AlterField(
            model_name='historicalcustomuser',
            name='bio',
            field=ateliersoude.fields.CleanHTMLField(blank=True, default='', verbose_name='bio'),
        ),
        migrations.AlterField(
            model_name='historicalorganization',
            name='description',
            field=ateliersoude.fields.CleanHTMLField(default='', verbose_name='Activity description'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=ateliersoude.fields.CleanHTMLField(default='', verbose_name='Activity description'),
        ),
    ]
