# Generated by Django 2.2 on 2019-06-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20190604_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorganization',
            name='fee_description',
            field=models.TextField(blank=True, default='', verbose_name='Explain how the contribution system works'),
        ),
        migrations.AddField(
            model_name='organization',
            name='fee_description',
            field=models.TextField(blank=True, default='', verbose_name='Explain how the contribution system works'),
        ),
    ]
