# Generated by Django 2.2 on 2019-07-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20190630_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorganization',
            name='email',
            field=models.EmailField(blank=True, max_length=200, verbose_name='Organization mail address'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, max_length=200, verbose_name='Organization mail address'),
        ),
    ]
