# Generated by Django 2.2 on 2019-07-15 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20190709_0955'),
        ('user', '0016_fee'),
    ]

    operations = [
    ]
