# Generated by Django 2.2.3 on 2020-01-31 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_auto_20200129_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='payment',
            field=models.CharField(blank=True, choices=[('1', 'Cash'), ('2', 'Bank transfer'), ('3', 'Bank check'), ('4', 'CB')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='membership',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='user.Organization'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
