# Generated by Django 2.2.3 on 2020-02-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20200131_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='payment',
            field=models.CharField(blank=True, choices=[('1', 'Espèces'), ('2', 'Online'), ('3', 'Chèque'), ('4', 'CB'), ('4', 'Gonettes')], default='1', max_length=1),
        ),
    ]
