# Generated by Django 2.2 on 2019-05-20 14:48

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_auto_20190507_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description',
            field=tinymce.models.HTMLField(default='', verbose_name='Place description'),
        ),
    ]
