# Generated by Django 2.2.3 on 2020-01-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0008_auto_20190604_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplace',
            name='is_visible',
            field=models.BooleanField(default=False, help_text='Est-ce que ce lieu est un lieu de votre organisation ? Si vous cochez oui, il sera visible sur votre page', verbose_name='place visibility'),
        ),
        migrations.AddField(
            model_name='place',
            name='is_visible',
            field=models.BooleanField(default=False, help_text='Est-ce que ce lieu est un lieu de votre organisation ? Si vous cochez oui, il sera visible sur votre page', verbose_name='place visibility'),
        ),
    ]
