# Generated by Django 3.2.2 on 2021-05-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0010_auto_20200115_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplace',
            name='is_visible',
            field=models.BooleanField(default=False, help_text='Est-ce que ce lieu est un lieu de votre organisation ? Si vous cochez oui, il sera visible sur votre page', null=True, verbose_name='Lieu principal'),
        ),
        migrations.AlterField(
            model_name='place',
            name='is_visible',
            field=models.BooleanField(default=False, help_text='Est-ce que ce lieu est un lieu de votre organisation ? Si vous cochez oui, il sera visible sur votre page', null=True, verbose_name='Lieu principal'),
        ),
    ]
