# Generated by Django 3.2.2 on 2021-12-27 13:23

from django.contrib.postgres.operations import CreateExtension
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('location', '0011_auto_20210517_1431'),
    ]

    operations = [CreateExtension('postgis')]
