# Generated by Django 3.2.2 on 2021-12-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0016_auto_20211228_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplace',
            name='zipcode',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='place',
            name='zipcode',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
    ]
