# Generated by Django 3.2.2 on 2021-12-30 14:57

import requests
from django.db import migrations

def set_zipcode(app, schema_editor):
    Place = app.get_model("location", "Place")
    for place in Place.objects.all():
        if place.location:
            point = requests.get(
                "https://api-adresse.data.gouv.fr/reverse/?"
                f"lat={place.location.y}&lon={place.location.x}"
            )
            if point.json()["features"]:
                postcode = point.json()["features"][0]["properties"]["postcode"]
                place.zipcode = postcode
                place.save()


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0017_auto_20211230_1557'),
    ]

    operations = [
        migrations.RunPython(
            set_zipcode, migrations.RunPython.noop
        )
    ]
