# Generated by Django 4.2.17 on 2025-11-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0018_auto_20211230_1557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalplace',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical place', 'verbose_name_plural': 'historical places'},
        ),
        migrations.AlterField(
            model_name='historicalplace',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
