# Generated by Django 2.2 on 2019-05-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190513_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_visible',
            field=models.BooleanField(default=False, help_text='Should people be able to see your profile?', verbose_name='Profile visible'),
        ),
    ]
