# Generated by Django 2.2 on 2019-05-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_historicalmembershipfee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmembershipfee',
            name='amount',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Amount paid'),
        ),
        migrations.AlterField(
            model_name='membershipfee',
            name='amount',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Amount paid'),
        ),
        migrations.AlterUniqueTogether(
            name='membershipfee',
            unique_together={('user', 'organization')},
        ),
    ]
