# Generated by Django 2.2 on 2019-05-27 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20190527_1405'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalMembershipFee',
            new_name='HistoricalMembership',
        ),
        migrations.RenameModel(
            old_name='MembershipFee',
            new_name='Membership',
        ),
        migrations.AlterModelOptions(
            name='historicalmembership',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical membership'},
        ),
        migrations.RemoveField(
            model_name='organization',
            name='subscriptions',
        ),
    ]
