# Generated by Django 2.2 on 2019-05-31 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_organization_actives'),
        ('user', '0011_auto_20190527_1523'),
    ]

    operations = [
    ]
