# Generated by Django 2.2 on 2019-06-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20190611_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorganization',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=200, verbose_name='Organization mail address'),
        ),
        migrations.AddField(
            model_name='historicalorganization',
            name='phone_number',
            field=models.CharField(blank=True, default='-', max_length=10, verbose_name='Organization phone number'),
        ),
        migrations.AddField(
            model_name='historicalorganization',
            name='website',
            field=models.URLField(blank=True, verbose_name='Organization website mail'),
        ),
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=200, verbose_name='Organization mail address'),
        ),
        migrations.AddField(
            model_name='organization',
            name='phone_number',
            field=models.CharField(blank=True, default='-', max_length=10, verbose_name='Organization phone number'),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True, verbose_name='Organization website mail'),
        ),
    ]
