# Generated by Django 2.2.3 on 2019-09-06 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_merge_20190715_1033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fee',
            options={'ordering': ['-date']},
        ),
    ]
