# Generated by Django 2.2.3 on 2020-01-29 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20200129_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='fee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Fee'),
        ),
    ]
