# Generated by Django 2.2.4 on 2020-08-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_auto_20200201_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='payment',
            field=models.CharField(blank=True, choices=[('1', 'Espèces'), ('2', 'Online'), ('3', 'Chèque'), ('4', 'CB'), ('5', 'Gonettes')], default='1', max_length=1),
        ),
    ]
