# Generated by Django 3.2.2 on 2021-05-17 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_auto_20200826_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fees', to='user.membership'),
        ),
        migrations.AddField(
            model_name='historicalmembership',
            name='disabled',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='historicalorganization',
            name='membership_system',
            field=models.CharField(choices=[('date_year', "L'adhésion dure un an à partir de la date de la première contribution."), ('date_month', "L'adhésion dure un mois à partir de la date de la première contribution."), ('year', "L'adhésion est pour l'année en cours et se renouvelle à chaque début d'année."), ('month', "L'adhésion est mensuelle, elle se renouvelle chaque début de mois.")], default='date_year', max_length=10),
        ),
        migrations.AddField(
            model_name='membership',
            name='disabled',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='membership_system',
            field=models.CharField(choices=[('date_year', "L'adhésion dure un an à partir de la date de la première contribution."), ('date_month', "L'adhésion dure un mois à partir de la date de la première contribution."), ('year', "L'adhésion est pour l'année en cours et se renouvelle à chaque début d'année."), ('month', "L'adhésion est mensuelle, elle se renouvelle chaque début de mois.")], default='date_year', max_length=10),
        ),
        migrations.AlterField(
            model_name='membership',
            name='fee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member', to='user.fee'),
        ),
    ]
