# Generated by Django 3.2.2 on 2021-05-25 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_auto_20210521_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmembership',
            name='first_payment',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='membership',
            name='first_payment',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
