# Generated by Django 3.2.2 on 2021-12-10 14:13

from django.db import migrations
from openrepairplatform.user.models import Membership


def update_old_fees(apps, schema_editor):
    for membership in Membership.objects.all():
        if membership.user.fees.all():
            for fee in membership.user.fees.all():
                membership.fees.add(fee)
            membership.update_first_payment()
            membership.computed_amount()
            membership.save()


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_auto_20210528_1346'),
    ]

    operations = [
        migrations.RunPython(update_old_fees, migrations.RunPython.noop),
    ]
