# Generated by Django 3.2.2 on 2021-12-10 14:13

from django.db import migrations


def update_old_fees(apps, schema_editor):
    User = apps.get_model('user', 'CustomUser')
    Membership = apps.get_model('user', 'Membership')
    Fee = apps.get_model('user', 'Fee')
    for membership in Membership.objects.all():
        if membership.user.fees.all():
            for fee in membership.user.fees.all():
                membership.fees.add(fee)
            membership.save()


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_auto_20210528_1346'),
    ]

    operations = [
        migrations.RunPython(update_old_fees, migrations.RunPython.noop),
    ]
