# Generated by Django 3.2.2 on 2021-12-14 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_alter_fee_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='user',
        ),
    ]
