# Generated by Django 4.2.17 on 2025-11-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_alter_fee_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalcustomuser',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical custom user', 'verbose_name_plural': 'historical custom users'},
        ),
        migrations.AlterModelOptions(
            name='historicalmembership',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical membership', 'verbose_name_plural': 'historical memberships'},
        ),
        migrations.AlterModelOptions(
            name='historicalorganization',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical organization', 'verbose_name_plural': 'historical organizations'},
        ),
        migrations.AlterField(
            model_name='historicalcustomuser',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalmembership',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalorganization',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
