# Generated by Django 4.2.17 on 2026-01-14 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_alter_historicalcustomuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorganization',
            name='child_organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.organization'),
        ),
        migrations.AddField(
            model_name='historicalorganization',
            name='parent_organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='child_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_organizations', to='user.organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='parent_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_organizations', to='user.organization'),
        ),
    ]
