# Generated by Django 4.2.17 on 2026-01-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_historicalorganization_child_organization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorganization',
            name='child_organization',
        ),
        migrations.RemoveField(
            model_name='historicalorganization',
            name='parent_organization',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='child_organization',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='parent_organization',
        ),
        migrations.AddField(
            model_name='organization',
            name='childs',
            field=models.ManyToManyField(blank=True, related_name='parents_of', to='user.organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children_of', to='user.organization'),
        ),
    ]
