# Generated by Django 4.2.17 on 2026-02-04 14:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_remove_historicalorganization_child_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='id_payment',
            field=models.CharField(blank=True, help_text='Identifiant de la transaction HelloAsso ou TiBillet', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalmembership',
            name='source',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('HELLOASSO', 'HELLOASSO'), ('TIBILLET', 'TIBILLET')], default='ADMIN', max_length=20, verbose_name="Origine de l'adhésion"),
        ),
        migrations.AddField(
            model_name='membership',
            name='source',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('HELLOASSO', 'HELLOASSO'), ('TIBILLET', 'TIBILLET')], default='ADMIN', max_length=20, verbose_name="Origine de l'adhésion"),
        ),
        migrations.AlterField(
            model_name='organization',
            name='childs',
            field=models.ManyToManyField(blank=True, related_name='parents_of', to='user.organization', verbose_name="Organisations 'filles'"),
        ),
        migrations.AlterField(
            model_name='organization',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children_of', to='user.organization', verbose_name="Organisations 'parentes'"),
        ),
        migrations.CreateModel(
            name='WebHook',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('signature_public_key', models.CharField(max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='user.organization')),
            ],
        ),
    ]
