# Generated by Django 4.2.17 on 2026-03-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_fee_id_payment_historicalmembership_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhook',
            name='signature_public_key',
        ),
        migrations.AddField(
            model_name='webhook',
            name='source',
            field=models.CharField(choices=[('HELLOASSO', 'HelloAsso'), ('TIBILLET', 'TiBillet')], default='HELLOASSO', max_length=20),
        ),
    ]
