# Generated by Django 2.2 on 2019-05-15 16:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20190513_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ends_at',
            field=models.TimeField(verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='starts_at',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Start time'),
        ),
    ]
