# Generated by Django 2.2 on 2019-05-27 12:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0012_historicalparticipation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalparticipation',
            name='amount',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Amount paid'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='amount',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Amount paid'),
        ),
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together={('user', 'event')},
        ),
    ]
