# Generated by Django 2.2 on 2019-06-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_auto_20190604_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='description',
            field=models.CharField(default='', max_length=100, verbose_name='Condition description'),
        ),
        migrations.AlterField(
            model_name='historicalcondition',
            name='description',
            field=models.CharField(default='', max_length=100, verbose_name='Condition description'),
        ),
    ]
