# Generated by Django 2.2 on 2019-07-08 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_auto_20190704_1514'),
        ('event', '0017_auto_20190630_1100'),
    ]

    operations = [
    ]
