# Generated by Django 2.2.3 on 2019-09-06 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0023_auto_20190823_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='fee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Fee'),
        ),
    ]
