# Generated by Django 2.2.3 on 2020-01-29 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0024_auto_20190906_1232'),
        ('event', '0020_auto_20190918_1538'),
    ]

    operations = [
    ]
