# Generated by Django 2.2.3 on 2020-02-08 10:33

import openrepairplatform.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0027_merge_20200208_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='collaborator',
            field=models.CharField(blank=True, max_length=100, verbose_name='In association with'),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=openrepairplatform.fields.CleanHTMLField(blank=True, verbose_name='Event extra description'),
        ),
        migrations.AddField(
            model_name='event',
            name='external',
            field=models.BooleanField(default=False, verbose_name='External booking ?'),
        ),
        migrations.AddField(
            model_name='event',
            name='external_url',
            field=models.URLField(blank=True, verbose_name='Link to an external website for booking or just for infos'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='collaborator',
            field=models.CharField(blank=True, max_length=100, verbose_name='In association with'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='description',
            field=openrepairplatform.fields.CleanHTMLField(blank=True, verbose_name='Event extra description'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='external',
            field=models.BooleanField(default=False, verbose_name='External booking ?'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='external_url',
            field=models.URLField(blank=True, verbose_name='Link to an external website for booking or just for infos'),
        ),
    ]
