# Generated by Django 2.2.3 on 2020-02-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0028_auto_20200208_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='booking',
            field=models.BooleanField(default=True, verbose_name='This event demands booking ?'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='booking',
            field=models.BooleanField(default=True, verbose_name='This event demands booking ?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='No booking limit ?'),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='No booking limit ?'),
        ),
    ]
