# Generated by Django 2.2.3 on 2020-02-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0029_auto_20200208_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalparticipation',
            name='payment',
            field=models.CharField(blank=True, choices=[('1', 'Espèces'), ('2', 'Online'), ('3', 'Chèque'), ('4', 'CB'), ('5', 'Gonettes')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='participation',
            name='payment',
            field=models.CharField(blank=True, choices=[('1', 'Espèces'), ('2', 'Online'), ('3', 'Chèque'), ('4', 'CB'), ('5', 'Gonettes')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='booking',
            field=models.BooleanField(default=True, verbose_name='This event demands internal booking ?'),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='booking',
            field=models.BooleanField(default=True, verbose_name='This event demands internal booking ?'),
        ),
    ]
