# Generated by Django 2.2.4 on 2020-11-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0030_auto_20200216_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='description',
            field=models.CharField(default='', max_length=300, verbose_name='Condition description'),
        ),
        migrations.AlterField(
            model_name='historicalcondition',
            name='description',
            field=models.CharField(default='', max_length=300, verbose_name='Condition description'),
        ),
    ]
