# Generated by Django 2.2.4 on 2020-12-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0033_auto_20201212_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='stuffs',
            field=models.ManyToManyField(blank=True, related_name='events', to='inventory.Stuff', verbose_name='Objets attendus'),
        ),
    ]
