# Generated by Django 3.2.2 on 2021-05-21 15:05

from django.db import migrations

FEES = []

def retrieve_participation_event(app, schema_editor):
    Participation = app.get_model("event", "Participation")
    for participation in Participation.objects.all():
        if participation.fee:
            FEES.append({"fee": participation.fee.pk, "event": participation.event.pk})


def link_event_to_fee(app, schema_editor):
    Fee = app.get_model("user", "Fee")
    Event = app.get_model("event", "Event")
    for fee_dict in FEES:
        fee = Fee.objects.filter(pk=fee_dict["fee"])
        event = Event.objects.get(pk=fee_dict["event"])
        fee.update(event=event)

class Migration(migrations.Migration):

    dependencies = [
        ('event', '0034_auto_20201220_1713'),
        ('user', '0027_auto_20210521_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalparticipation',
            name='fee',
        ),
        migrations.RunPython(
            retrieve_participation_event , migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name='participation',
            name='fee',
        ),
        migrations.RunPython(
            link_event_to_fee , migrations.RunPython.noop
        ),
    ]
