# Generated by Django 3.2.2 on 2021-05-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0035_auto_20210521_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='members_only',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='members_only',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
