# Generated by Django 3.2.2 on 2021-05-25 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0036_auto_20210525_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalparticipation',
            name='saved',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='saved',
        ),
    ]
