# Generated by Django 3.2.2 on 2021-09-08 14:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0040_auto_20210908_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='publish_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publication date and time'),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='publish_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publication date and time'),
        ),
    ]
