# Generated by Django 3.2.2 on 2023-03-29 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0041_auto_20210908_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
    ]
