# Generated by Django 4.2.17 on 2025-11-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0043_auto_20250121_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalactivity',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical activity', 'verbose_name_plural': 'historical Activities'},
        ),
        migrations.AlterModelOptions(
            name='historicalactivitycategory',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical activity category', 'verbose_name_plural': 'historical activity categorys'},
        ),
        migrations.AlterModelOptions(
            name='historicalcondition',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical condition', 'verbose_name_plural': 'historical conditions'},
        ),
        migrations.AlterModelOptions(
            name='historicalevent',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical event', 'verbose_name_plural': 'historical events'},
        ),
        migrations.AlterModelOptions(
            name='historicalparticipation',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical participation', 'verbose_name_plural': 'historical participations'},
        ),
        migrations.AlterField(
            model_name='historicalactivity',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalactivitycategory',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalcondition',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalparticipation',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
