# Generated by Django 4.2.17 on 2026-03-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0044_alter_historicalactivity_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='booking',
            field=models.BooleanField(default=False, verbose_name='Réservation nécessaire ?'),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='booking',
            field=models.BooleanField(default=False, verbose_name='Réservation nécessaire ?'),
        ),
    ]
