# Generated by Django 2.2 on 2019-05-07 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20190507_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='places', to='user.Organization'),
        ),
    ]
