# Generated by Django 2.2 on 2019-05-21 07:49

import ateliersoude.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_historicalcustomuser_historicalorganization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0004_auto_20190507_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPlace',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(default='', verbose_name='Place description')),
                ('category', models.CharField(default='Other', max_length=100)),
                ('slug', models.SlugField(blank=True, default='')),
                ('address', models.CharField(max_length=255, verbose_name='street address')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('picture', models.TextField(blank=True, max_length=100, null=True, validators=[ateliersoude.utils.validate_image], verbose_name='Image')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.Organization')),
            ],
            options={
                'verbose_name': 'historical place',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
