# Generated by Django 2.2 on 2019-05-21 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_historicalplace'),
        ('location', '0005_auto_20190520_1648'),
    ]

    operations = [
    ]
