# Generated by Django 2.2 on 2019-06-04 10:54

import ateliersoude.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_auto_20190521_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplace',
            name='description',
            field=ateliersoude.fields.CleanHTMLField(default='', verbose_name='Place description'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=ateliersoude.fields.CleanHTMLField(default='', verbose_name='Place description'),
        ),
    ]
