# Generated by Django 2.2.3 on 2020-01-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0009_auto_20200115_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplace',
            name='is_visible',
            field=models.NullBooleanField(default=False, help_text='Est-ce que ce lieu est un lieu de votre organisation ? Si vous cochez oui, il sera visible sur votre page', verbose_name='Lieu principal'),
        ),
        migrations.AlterField(
            model_name='place',
            name='is_visible',
            field=models.NullBooleanField(default=False, help_text='Est-ce que ce lieu est un lieu de votre organisation ? Si vous cochez oui, il sera visible sur votre page', verbose_name='Lieu principal'),
        ),
    ]
